// Generated by CoffeeScript 1.4.0
(function() {
  var elem, rule, wrapper, _i, _j, _len, _len1, _ref, _ref1;

  _ref = document.styleSheets[0].cssRules;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    rule = _ref[_i];
    _ref1 = document.querySelectorAll(rule.selectorText);
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      elem = _ref1[_j];
      wrapper = document.createElement('span');
      wrapper.innerHTML = elem.innerHTML;
      wrapper.style.cssText = rule.style.cssText;
      elem.innerHTML = "<span style=\"" + rule.style.cssText + "\">" + elem.innerHTML + "</span>";
    }
  }

}).call(this);
